-- Run this once in Supabase Dashboard → SQL Editor.
-- The application server uses the service-role connection for these writes
-- and reads, while browser roles are denied access by RLS.

create table if not exists public.visitors (
  id bigint generated by default as identity primary key,
  user_id uuid not null unique references auth.users(id) on delete cascade,
  name text not null,
  email text not null,
  first_visit_at timestamptz not null default timezone('utc', now()),
  last_visit_at timestamptz not null default timezone('utc', now()),
  visit_count integer not null default 1 check (visit_count > 0),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create index if not exists visitors_last_visit_at_idx
  on public.visitors (last_visit_at desc);

alter table public.visitors enable row level security;

drop policy if exists "Visitors are private" on public.visitors;
create policy "Visitors are private"
  on public.visitors
  for all
  to anon, authenticated
  using (false)
  with check (false);

create or replace function public.record_visitor_visit(
  p_user_id uuid,
  p_name text,
  p_email text
)
returns public.visitors
language plpgsql
security definer
set search_path = public
as $$
declare
  visitor public.visitors;
begin
  insert into public.visitors (user_id, name, email, visit_count)
  values (p_user_id, p_name, lower(p_email), 1)
  on conflict (user_id) do update
    set name = excluded.name,
        email = excluded.email,
        last_visit_at = timezone('utc', now()),
        visit_count = public.visitors.visit_count + 1,
        updated_at = timezone('utc', now())
  returning * into visitor;

  return visitor;
end;
$$;

revoke all on table public.visitors from anon, authenticated;
revoke all on function public.record_visitor_visit(uuid, text, text) from public, anon, authenticated;
grant execute on function public.record_visitor_visit(uuid, text, text) to service_role;